name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - uses: actions/checkout@v4

    # Set up Node.js environment
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Install Node.js dependencies
    - name: Install dependencies
      run: npm ci

    # Install Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Install Docker
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    # Pull the Docker image
    - name: Pull Docker Image
      run: docker pull automaticbytes/demo-app

    # Run Playwright tests
    - name: Run Playwright Tests
      run: npx playwright test

    # Upload Playwright report as an artifact
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30